# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hdf5_manager.ui'
#
# Created: Sun Apr 19 22:41:40 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1045, 866)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.fileGridFrame = QtGui.QFrame(self.centralwidget)
        self.fileGridFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fileGridFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fileGridFrame.setObjectName(_fromUtf8("fileGridFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.fileGridFrame)
        self.gridLayout_2.setMargin(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.workingDirectory = QtGui.QLineEdit(self.fileGridFrame)
        self.workingDirectory.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.workingDirectory.setObjectName(_fromUtf8("workingDirectory"))
        self.gridLayout_2.addWidget(self.workingDirectory, 1, 0, 1, 1)
        self.experimentTree = QtGui.QTreeWidget(self.fileGridFrame)
        self.experimentTree.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.experimentTree.setFrameShadow(QtGui.QFrame.Sunken)
        self.experimentTree.setMidLineWidth(0)
        self.experimentTree.setAnimated(False)
        self.experimentTree.setObjectName(_fromUtf8("experimentTree"))
        self.experimentTree.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.experimentTree.headerItem().setTextAlignment(2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.experimentTree.header().setVisible(True)
        self.experimentTree.header().setCascadingSectionResizes(False)
        self.experimentTree.header().setDefaultSectionSize(200)
        self.experimentTree.header().setMinimumSectionSize(20)
        self.gridLayout_2.addWidget(self.experimentTree, 2, 0, 1, 1)
        self.horizontalWidget = QtGui.QWidget(self.fileGridFrame)
        self.horizontalWidget.setObjectName(_fromUtf8("horizontalWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.loadDirectoryBtn = QtGui.QPushButton(self.horizontalWidget)
        self.loadDirectoryBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.loadDirectoryBtn.setObjectName(_fromUtf8("loadDirectoryBtn"))
        self.horizontalLayout.addWidget(self.loadDirectoryBtn)
        self.reloadDirectoryBtn = QtGui.QPushButton(self.horizontalWidget)
        self.reloadDirectoryBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.reloadDirectoryBtn.setObjectName(_fromUtf8("reloadDirectoryBtn"))
        self.horizontalLayout.addWidget(self.reloadDirectoryBtn)
        self.gridLayout_2.addWidget(self.horizontalWidget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.fileGridFrame, 0, 0, 2, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(440, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.dataTab = QtGui.QWidget()
        self.dataTab.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.dataTab.setObjectName(_fromUtf8("dataTab"))
        self.experimentGridFrame = QtGui.QFrame(self.dataTab)
        self.experimentGridFrame.setGeometry(QtCore.QRect(10, 10, 411, 531))
        self.experimentGridFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.experimentGridFrame.setMaximumSize(QtCore.QSize(450, 16777215))
        self.experimentGridFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.experimentGridFrame.setObjectName(_fromUtf8("experimentGridFrame"))
        self.gridLayout = QtGui.QGridLayout(self.experimentGridFrame)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setContentsMargins(6, 4, 6, 4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalWidget1 = QtGui.QWidget(self.experimentGridFrame)
        self.horizontalWidget1.setMaximumSize(QtCore.QSize(16777215, 28))
        self.horizontalWidget1.setObjectName(_fromUtf8("horizontalWidget1"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_2 = QtGui.QLabel(self.horizontalWidget1)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.addExpRowBtn = QtGui.QPushButton(self.horizontalWidget1)
        self.addExpRowBtn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addExpRowBtn.setFont(font)
        self.addExpRowBtn.setObjectName(_fromUtf8("addExpRowBtn"))
        self.horizontalLayout_7.addWidget(self.addExpRowBtn)
        self.removeExpRowBtn = QtGui.QPushButton(self.horizontalWidget1)
        self.removeExpRowBtn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.removeExpRowBtn.setFont(font)
        self.removeExpRowBtn.setObjectName(_fromUtf8("removeExpRowBtn"))
        self.horizontalLayout_7.addWidget(self.removeExpRowBtn)
        self.gridLayout.addWidget(self.horizontalWidget1, 7, 0, 1, 1)
        self.dataSetAttributes = QtGui.QTableWidget(self.experimentGridFrame)
        self.dataSetAttributes.setMaximumSize(QtCore.QSize(16777215, 62))
        self.dataSetAttributes.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dataSetAttributes.setRowCount(3)
        self.dataSetAttributes.setColumnCount(2)
        self.dataSetAttributes.setObjectName(_fromUtf8("dataSetAttributes"))
        self.dataSetAttributes.horizontalHeader().setVisible(False)
        self.dataSetAttributes.horizontalHeader().setDefaultSectionSize(160)
        self.dataSetAttributes.horizontalHeader().setHighlightSections(True)
        self.dataSetAttributes.horizontalHeader().setStretchLastSection(True)
        self.dataSetAttributes.verticalHeader().setVisible(False)
        self.dataSetAttributes.verticalHeader().setDefaultSectionSize(20)
        self.dataSetAttributes.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.dataSetAttributes, 11, 0, 1, 1)
        self.horizontalWidget2 = QtGui.QWidget(self.experimentGridFrame)
        self.horizontalWidget2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalWidget2.setObjectName(_fromUtf8("horizontalWidget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.saveAttributeChangeBtn = QtGui.QPushButton(self.horizontalWidget2)
        self.saveAttributeChangeBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.saveAttributeChangeBtn.setObjectName(_fromUtf8("saveAttributeChangeBtn"))
        self.horizontalLayout_2.addWidget(self.saveAttributeChangeBtn)
        self.restoreAttributesBtn = QtGui.QPushButton(self.horizontalWidget2)
        self.restoreAttributesBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.restoreAttributesBtn.setObjectName(_fromUtf8("restoreAttributesBtn"))
        self.horizontalLayout_2.addWidget(self.restoreAttributesBtn)
        self.gridLayout.addWidget(self.horizontalWidget2, 13, 0, 1, 1)
        self.groupAttributes = QtGui.QTableWidget(self.experimentGridFrame)
        self.groupAttributes.setMaximumSize(QtCore.QSize(16777215, 102))
        self.groupAttributes.setAutoFillBackground(False)
        self.groupAttributes.setStyleSheet(_fromUtf8("background-color: rgb(240, 255, 244);"))
        self.groupAttributes.setFrameShape(QtGui.QFrame.StyledPanel)
        self.groupAttributes.setFrameShadow(QtGui.QFrame.Sunken)
        self.groupAttributes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.groupAttributes.setTextElideMode(QtCore.Qt.ElideRight)
        self.groupAttributes.setRowCount(5)
        self.groupAttributes.setColumnCount(2)
        self.groupAttributes.setObjectName(_fromUtf8("groupAttributes"))
        self.groupAttributes.horizontalHeader().setVisible(False)
        self.groupAttributes.horizontalHeader().setCascadingSectionResizes(False)
        self.groupAttributes.horizontalHeader().setDefaultSectionSize(160)
        self.groupAttributes.horizontalHeader().setHighlightSections(True)
        self.groupAttributes.horizontalHeader().setMinimumSectionSize(56)
        self.groupAttributes.horizontalHeader().setSortIndicatorShown(False)
        self.groupAttributes.horizontalHeader().setStretchLastSection(True)
        self.groupAttributes.verticalHeader().setVisible(False)
        self.groupAttributes.verticalHeader().setCascadingSectionResizes(False)
        self.groupAttributes.verticalHeader().setDefaultSectionSize(20)
        self.groupAttributes.verticalHeader().setHighlightSections(False)
        self.groupAttributes.verticalHeader().setMinimumSectionSize(20)
        self.groupAttributes.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.groupAttributes, 8, 0, 1, 1)
        self.expInfoLabel = QtGui.QLabel(self.experimentGridFrame)
        self.expInfoLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.expInfoLabel.setFont(font)
        self.expInfoLabel.setObjectName(_fromUtf8("expInfoLabel"))
        self.gridLayout.addWidget(self.expInfoLabel, 0, 0, 1, 1)
        self.horizontalWidget3 = QtGui.QWidget(self.experimentGridFrame)
        self.horizontalWidget3.setMaximumSize(QtCore.QSize(1677215, 28))
        self.horizontalWidget3.setObjectName(_fromUtf8("horizontalWidget3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalWidget3)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label = QtGui.QLabel(self.horizontalWidget3)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_8.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.addGroupRowBtn = QtGui.QPushButton(self.horizontalWidget3)
        self.addGroupRowBtn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addGroupRowBtn.setFont(font)
        self.addGroupRowBtn.setObjectName(_fromUtf8("addGroupRowBtn"))
        self.horizontalLayout_8.addWidget(self.addGroupRowBtn)
        self.removeGroupRowBtn = QtGui.QPushButton(self.horizontalWidget3)
        self.removeGroupRowBtn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.removeGroupRowBtn.setFont(font)
        self.removeGroupRowBtn.setObjectName(_fromUtf8("removeGroupRowBtn"))
        self.horizontalLayout_8.addWidget(self.removeGroupRowBtn)
        self.gridLayout.addWidget(self.horizontalWidget3, 9, 0, 1, 1)
        self.horizontalWidget4 = QtGui.QWidget(self.experimentGridFrame)
        self.horizontalWidget4.setMaximumSize(QtCore.QSize(16777215, 28))
        self.horizontalWidget4.setObjectName(_fromUtf8("horizontalWidget4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalWidget4)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.addDatasetRowBtn = QtGui.QPushButton(self.horizontalWidget4)
        self.addDatasetRowBtn.setMinimumSize(QtCore.QSize(0, 20))
        self.addDatasetRowBtn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addDatasetRowBtn.setFont(font)
        self.addDatasetRowBtn.setObjectName(_fromUtf8("addDatasetRowBtn"))
        self.horizontalLayout_9.addWidget(self.addDatasetRowBtn)
        self.removeDatasetRowBtn = QtGui.QPushButton(self.horizontalWidget4)
        self.removeDatasetRowBtn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.removeDatasetRowBtn.setFont(font)
        self.removeDatasetRowBtn.setObjectName(_fromUtf8("removeDatasetRowBtn"))
        self.horizontalLayout_9.addWidget(self.removeDatasetRowBtn)
        self.gridLayout.addWidget(self.horizontalWidget4, 12, 0, 1, 1)
        self.experimentAttributes = QtGui.QTableWidget(self.experimentGridFrame)
        self.experimentAttributes.setMinimumSize(QtCore.QSize(0, 162))
        self.experimentAttributes.setMaximumSize(QtCore.QSize(16777215, 162))
        self.experimentAttributes.setStyleSheet(_fromUtf8("background-color: rgb(231, 234, 255);"))
        self.experimentAttributes.setTextElideMode(QtCore.Qt.ElideLeft)
        self.experimentAttributes.setRowCount(8)
        self.experimentAttributes.setColumnCount(2)
        self.experimentAttributes.setObjectName(_fromUtf8("experimentAttributes"))
        self.experimentAttributes.horizontalHeader().setVisible(False)
        self.experimentAttributes.horizontalHeader().setDefaultSectionSize(160)
        self.experimentAttributes.horizontalHeader().setStretchLastSection(True)
        self.experimentAttributes.verticalHeader().setVisible(False)
        self.experimentAttributes.verticalHeader().setDefaultSectionSize(20)
        self.experimentAttributes.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.experimentAttributes, 1, 0, 1, 1)
        self.gridFrame = QtGui.QFrame(self.dataTab)
        self.gridFrame.setGeometry(QtCore.QRect(10, 550, 411, 131))
        self.gridFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gridFrame.setObjectName(_fromUtf8("gridFrame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridFrame)
        self.gridLayout_6.setMargin(6)
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_5 = QtGui.QLabel(self.gridFrame)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalWidget5 = QtGui.QWidget(self.gridFrame)
        self.horizontalWidget5.setObjectName(_fromUtf8("horizontalWidget5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalWidget5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.genericRadioBtn = QtGui.QRadioButton(self.horizontalWidget5)
        self.genericRadioBtn.setObjectName(_fromUtf8("genericRadioBtn"))
        self.plottingChoice = QtGui.QButtonGroup(MainWindow)
        self.plottingChoice.setObjectName(_fromUtf8("plottingChoice"))
        self.plottingChoice.addButton(self.genericRadioBtn)
        self.horizontalLayout_5.addWidget(self.genericRadioBtn)
        self.timeSeriesRadioBtn = QtGui.QRadioButton(self.horizontalWidget5)
        self.timeSeriesRadioBtn.setObjectName(_fromUtf8("timeSeriesRadioBtn"))
        self.plottingChoice.addButton(self.timeSeriesRadioBtn)
        self.horizontalLayout_5.addWidget(self.timeSeriesRadioBtn)
        self.spikesRadioBtn = QtGui.QRadioButton(self.horizontalWidget5)
        self.spikesRadioBtn.setObjectName(_fromUtf8("spikesRadioBtn"))
        self.plottingChoice.addButton(self.spikesRadioBtn)
        self.horizontalLayout_5.addWidget(self.spikesRadioBtn)
        self.threeDRadioBtn = QtGui.QRadioButton(self.horizontalWidget5)
        self.threeDRadioBtn.setObjectName(_fromUtf8("threeDRadioBtn"))
        self.plottingChoice.addButton(self.threeDRadioBtn)
        self.horizontalLayout_5.addWidget(self.threeDRadioBtn)
        self.gridLayout_6.addWidget(self.horizontalWidget5, 1, 0, 1, 1)
        self.dataSetSelection = QtGui.QLineEdit(self.gridFrame)
        self.dataSetSelection.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dataSetSelection.setObjectName(_fromUtf8("dataSetSelection"))
        self.gridLayout_6.addWidget(self.dataSetSelection, 2, 0, 1, 1)
        self.horizontalFrame = QtGui.QFrame(self.gridFrame)
        self.horizontalFrame.setObjectName(_fromUtf8("horizontalFrame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.plotDataBtn = QtGui.QPushButton(self.horizontalFrame)
        self.plotDataBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.plotDataBtn.setObjectName(_fromUtf8("plotDataBtn"))
        self.horizontalLayout_3.addWidget(self.plotDataBtn)
        self.addToPlotBtn = QtGui.QPushButton(self.horizontalFrame)
        self.addToPlotBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.addToPlotBtn.setObjectName(_fromUtf8("addToPlotBtn"))
        self.horizontalLayout_3.addWidget(self.addToPlotBtn)
        self.gridLayout_6.addWidget(self.horizontalFrame, 3, 0, 1, 1)
        self.gridFrame1 = QtGui.QFrame(self.dataTab)
        self.gridFrame1.setGeometry(QtCore.QRect(10, 690, 411, 61))
        self.gridFrame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gridFrame1.setObjectName(_fromUtf8("gridFrame1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridFrame1)
        self.gridLayout_5.setMargin(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalWidget6 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget6.setObjectName(_fromUtf8("horizontalWidget6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalWidget6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.launchiPythonBtn = QtGui.QPushButton(self.horizontalWidget6)
        self.launchiPythonBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.launchiPythonBtn.setObjectName(_fromUtf8("launchiPythonBtn"))
        self.horizontalLayout_6.addWidget(self.launchiPythonBtn)
        self.sendToConsoleBtn = QtGui.QPushButton(self.horizontalWidget6)
        self.sendToConsoleBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.sendToConsoleBtn.setObjectName(_fromUtf8("sendToConsoleBtn"))
        self.horizontalLayout_6.addWidget(self.sendToConsoleBtn)
        self.plotNameSpaceBtn = QtGui.QPushButton(self.horizontalWidget6)
        self.plotNameSpaceBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.plotNameSpaceBtn.setObjectName(_fromUtf8("plotNameSpaceBtn"))
        self.horizontalLayout_6.addWidget(self.plotNameSpaceBtn)
        self.gridLayout_5.addWidget(self.horizontalWidget6, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridFrame1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dataTab, _fromUtf8(""))
        self.notesTab = QtGui.QWidget()
        self.notesTab.setObjectName(_fromUtf8("notesTab"))
        self.gridFrame2 = QtGui.QFrame(self.notesTab)
        self.gridFrame2.setGeometry(QtCore.QRect(10, 10, 421, 741))
        self.gridFrame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gridFrame2.setObjectName(_fromUtf8("gridFrame2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridFrame2)
        self.gridLayout_4.setMargin(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.experimentNotesValue = QtGui.QTextEdit(self.gridFrame2)
        self.experimentNotesValue.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.experimentNotesValue.setObjectName(_fromUtf8("experimentNotesValue"))
        self.gridLayout_4.addWidget(self.experimentNotesValue, 1, 0, 1, 1)
        self.groupNotesValue = QtGui.QTextEdit(self.gridFrame2)
        self.groupNotesValue.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.groupNotesValue.setObjectName(_fromUtf8("groupNotesValue"))
        self.gridLayout_4.addWidget(self.groupNotesValue, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridFrame2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridFrame2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.horizontalWidget7 = QtGui.QWidget(self.gridFrame2)
        self.horizontalWidget7.setMinimumSize(QtCore.QSize(0, 20))
        self.horizontalWidget7.setObjectName(_fromUtf8("horizontalWidget7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalWidget7)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.saveNotesBtn = QtGui.QPushButton(self.horizontalWidget7)
        self.saveNotesBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.saveNotesBtn.setObjectName(_fromUtf8("saveNotesBtn"))
        self.horizontalLayout_4.addWidget(self.saveNotesBtn)
        self.restoreNotesBtn = QtGui.QPushButton(self.horizontalWidget7)
        self.restoreNotesBtn.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.restoreNotesBtn.setObjectName(_fromUtf8("restoreNotesBtn"))
        self.horizontalLayout_4.addWidget(self.restoreNotesBtn)
        self.gridLayout_4.addWidget(self.horizontalWidget7, 4, 0, 1, 1)
        self.tabWidget.addTab(self.notesTab, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.experimentTree.setSortingEnabled(True)
        self.experimentTree.headerItem().setText(0, _translate("MainWindow", "Data", None))
        self.experimentTree.headerItem().setText(1, _translate("MainWindow", "Size", None))
        self.experimentTree.headerItem().setText(2, _translate("MainWindow", "Type", None))
        self.loadDirectoryBtn.setText(_translate("MainWindow", "Load directory", None))
        self.reloadDirectoryBtn.setText(_translate("MainWindow", "Reload directory", None))
        self.label_2.setText(_translate("MainWindow", "Group attributes", None))
        self.addExpRowBtn.setText(_translate("MainWindow", "+", None))
        self.removeExpRowBtn.setText(_translate("MainWindow", "-", None))
        self.saveAttributeChangeBtn.setText(_translate("MainWindow", "Save Attribute Changes ", None))
        self.restoreAttributesBtn.setText(_translate("MainWindow", "Restore Attributes", None))
        self.expInfoLabel.setText(_translate("MainWindow", "Experiment attributes", None))
        self.label.setText(_translate("MainWindow", "Data-set attributes", None))
        self.addGroupRowBtn.setText(_translate("MainWindow", "+", None))
        self.removeGroupRowBtn.setText(_translate("MainWindow", "-", None))
        self.addDatasetRowBtn.setText(_translate("MainWindow", "+", None))
        self.removeDatasetRowBtn.setText(_translate("MainWindow", "-", None))
        self.label_5.setText(_translate("MainWindow", "Plotting", None))
        self.genericRadioBtn.setText(_translate("MainWindow", "Generic", None))
        self.timeSeriesRadioBtn.setText(_translate("MainWindow", "TimeSeries", None))
        self.spikesRadioBtn.setText(_translate("MainWindow", "Spikes", None))
        self.threeDRadioBtn.setText(_translate("MainWindow", "3D", None))
        self.plotDataBtn.setText(_translate("MainWindow", "Plot data", None))
        self.addToPlotBtn.setText(_translate("MainWindow", "Add to plot", None))
        self.launchiPythonBtn.setText(_translate("MainWindow", "Launch iPython", None))
        self.sendToConsoleBtn.setText(_translate("MainWindow", "Send to concole", None))
        self.plotNameSpaceBtn.setText(_translate("MainWindow", "Print NameSpace", None))
        self.label_6.setText(_translate("MainWindow", "Analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), _translate("MainWindow", "Data", None))
        self.label_3.setText(_translate("MainWindow", "Experiment notes", None))
        self.label_4.setText(_translate("MainWindow", "Group notes", None))
        self.saveNotesBtn.setText(_translate("MainWindow", "Save Notes", None))
        self.restoreNotesBtn.setText(_translate("MainWindow", "Restore Notes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notesTab), _translate("MainWindow", "Notes", None))

